import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home';
import { AboutComponent } from './components/about/about';
import { ObservableComponent } from './components/observable/observable';
import { ComputedComponent } from './components/computed/computed';
import { SubjectComponent } from './components/subject/subject';
import { AdresseComponent } from './components/adresse/adresse';
import { StagiaireComponent } from './components/stagiaire/stagiaire';
import { CalculComponent } from './components/calcul/calcul';
import { TableauComponent } from './components/tableau/tableau';
import { NotFoundComponent } from './components/not-found/not-found';
import { FormulaireSimpleComponent } from './components/formulaire-simple/formulaire-simple';
import { CalculetteComponent } from './components/calculette/calculette';
import { FormulaireReactifComponent } from './components/formulaire-reactif/formulaire-reactif';
import { FormulaireReactifBuilderComponent } from './components/formulaire-reactif-builder/formulaire-reactif-builder';
import { CommentComponent } from './components/comment/comment';
import { FormulaireSignalComponent } from './components/formulaire-signal/formulaire-signal';
import { PersonneComponent } from './components/personne-component/personne-component';
import { PereComponent } from './components/pere/pere';
import { PrimeurComponent } from './components/primeur/primeur';
import { ParentComponent } from './components/parent/parent';
import { ClavierComponent } from './components/clavier/clavier';
import { PaysComponent } from './components/pays/pays';
import { ContainerComponent } from './components/container/container';
import { TchatComponent } from './components/tchat/tchat';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'about', component: AboutComponent },
  { path: 'adresse', component: AdresseComponent },
  { path: 'address', redirectTo: '/adresse' },
  { path: 'stagiaire/:nom/:prenom', component: StagiaireComponent },
  { path: 'calcul/:op', component: CalculComponent },
  { path: 'tableau/:indice', component: TableauComponent },
  { path: 'observable', component: ObservableComponent },
  { path: 'subject', component: SubjectComponent },
  { path: 'computed', component: ComputedComponent },
  { path: 'formulaire', component: FormulaireSimpleComponent },
  { path: 'calculette', component: CalculetteComponent },
  { path: 'reactive', component: FormulaireReactifComponent },
  { path: 'builder', component: FormulaireReactifBuilderComponent },
  { path: 'signal-form', component: FormulaireSignalComponent },
  { path: 'comment', component: CommentComponent },
  { path: 'personne', component: PersonneComponent },
  { path: 'pere', component: PereComponent },
  { path: 'primeur', component: PrimeurComponent },
  { path: 'parent', component: ParentComponent },
  { path: 'clavier', component: ClavierComponent },
  { path: 'pays', component: PaysComponent },
  { path: 'container', component: ContainerComponent },
  { path: 'chat', component: TchatComponent },

  //{ path: '**', component: NotFoundComponent },
  { path: 'not-found', component: NotFoundComponent },
  { path: '**', redirectTo: 'not-found' },
];
